openapi: 3.0.3
info:
  title: 'Booking.com API Documentation'
  description: 'Example project cloning booking.com built with Laravel as part of Course in LaravelDaily.com'
  version: 1.0.0
servers:
  -
    url: 'http://booking-com-simulation-laravel.test'
paths:
  /api/auth/register:
    post:
      summary: 'Register a new user.'
      operationId: registerANewUser
      description: '[Creates a new user and returns a token for authentication.]'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  access_token: 1|a9ZcYzIrLURVGx6Xe41HKj1CrNsxRxe4pLA2oISo
                properties:
                  access_token:
                    type: string
                    example: 1|a9ZcYzIrLURVGx6Xe41HKj1CrNsxRxe4pLA2oISo
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The selected role id is invalid.'
                  errors:
                    role_id:
                      - 'The selected role id is invalid.'
                properties:
                  message:
                    type: string
                    example: 'The selected role id is invalid.'
                  errors:
                    type: object
                    properties:
                      role_id:
                        type: array
                        example:
                          - 'The selected role id is invalid.'
                        items:
                          type: string
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vjsoxgflpadkawiltji
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: muller.tristin@example.com
                password:
                  type: string
                  description: ''
                  example: ullam
                role_id:
                  type: string
                  description: ''
                  example: aperiam
              required:
                - name
                - email
                - password
                - role_id
      security: []
  /api/owner/properties:
    get:
      summary: 'Properties list - **INCOMPLETE**'
      operationId: propertiesListINCOMPLETE
      description: '[List of owners properties]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                properties:
                  success:
                    type: boolean
                    example: true
      tags:
        - Owner
    post:
      summary: 'Store property'
      operationId: storeProperty
      description: '[Stores new property of the owner]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  name: 'My property'
                  city_id: 1
                  address_street: 'Street Address 1'
                  address_postcode: '12345'
                  owner_id: 2
                  updated_at: '2023-05-10T07:07:45.000000Z'
                  created_at: '2023-05-10T07:07:45.000000Z'
                  id: 1
                  city:
                    id: 1
                    country_id: 1
                    name: 'New York'
                    lat: '40.7127760'
                    long: '-74.0059740'
                    created_at: '2023-05-10T07:07:45.000000Z'
                    updated_at: '2023-05-10T07:07:45.000000Z'
                    country:
                      id: 1
                      name: 'United States'
                      lat: '37.0902400'
                      long: '-95.7128910'
                      created_at: '2023-05-10T07:07:45.000000Z'
                      updated_at: '2023-05-10T07:07:45.000000Z'
                properties:
                  name:
                    type: string
                    example: 'My property'
                  city_id:
                    type: integer
                    example: 1
                  address_street:
                    type: string
                    example: 'Street Address 1'
                  address_postcode:
                    type: string
                    example: '12345'
                  owner_id:
                    type: integer
                    example: 2
                  updated_at:
                    type: string
                    example: '2023-05-10T07:07:45.000000Z'
                  created_at:
                    type: string
                    example: '2023-05-10T07:07:45.000000Z'
                  id:
                    type: integer
                    example: 1
                  city:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      country_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'New York'
                      lat:
                        type: string
                        example: '40.7127760'
                      long:
                        type: string
                        example: '-74.0059740'
                      created_at:
                        type: string
                        example: '2023-05-10T07:07:45.000000Z'
                      updated_at:
                        type: string
                        example: '2023-05-10T07:07:45.000000Z'
                      country:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: 'United States'
                          lat:
                            type: string
                            example: '37.0902400'
                          long:
                            type: string
                            example: '-95.7128910'
                          created_at:
                            type: string
                            example: '2023-05-10T07:07:45.000000Z'
                          updated_at:
                            type: string
                            example: '2023-05-10T07:07:45.000000Z'
      tags:
        - Owner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: iure
                city_id:
                  type: string
                  description: ''
                  example: neque
                address_street:
                  type: string
                  description: ''
                  example: molestiae
                address_postcode:
                  type: string
                  description: ''
                  example: aut
              required:
                - name
                - city_id
                - address_street
                - address_postcode
  '/api/owner/properties/{property_id}/photos':
    post:
      summary: 'Add a photo to a property'
      operationId: addAPhotoToAProperty
      description: '[Adds a photo to a property and returns the filename, thumbnail and position of the photo]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  filename: 'http://localhost:8000/storage/properties/1/photos/1/IMG_20190601_123456.jpg'
                  thumbnail: 'http://localhost:8000/storage/properties/1/photos/1/conversions/thumbnail.jpg'
                  position: 1
                properties:
                  filename:
                    type: string
                    example: 'http://localhost:8000/storage/properties/1/photos/1/IMG_20190601_123456.jpg'
                  thumbnail:
                    type: string
                    example: 'http://localhost:8000/storage/properties/1/photos/1/conversions/thumbnail.jpg'
                  position:
                    type: integer
                    example: 1
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The photo must be an image.'
                  errors:
                    photo:
                      - 'The photo must be an image.'
                properties:
                  message:
                    type: string
                    example: 'The photo must be an image.'
                  errors:
                    type: object
                    properties:
                      photo:
                        type: array
                        example:
                          - 'The photo must be an image.'
                        items:
                          type: string
      tags:
        - Owner
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
                  description: 'Must be an image. Must not be greater than 5000 kilobytes.'
    parameters:
      -
        in: path
        name: property_id
        description: 'The ID of the property.'
        example: 10
        required: true
        schema:
          type: integer
  '/api/owner/properties/{property_id}/photos/{photo_id}/reorder/{newPosition}':
    post:
      summary: 'Reorder photos of a property'
      operationId: reorderPhotosOfAProperty
      description: '[Reorders photos of a property and returns the new position of the photo]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  newPosition: 2
                properties:
                  newPosition:
                    type: integer
                    example: 2
      tags:
        - Owner
    parameters:
      -
        in: path
        name: property_id
        description: 'The ID of the property.'
        example: 9
        required: true
        schema:
          type: integer
      -
        in: path
        name: photo_id
        description: 'The ID of the photo.'
        example: 2
        required: true
        schema:
          type: integer
      -
        in: path
        name: newPosition
        description: 'The new position of the photo.'
        example: 2
        required: true
        schema:
          type: integer
  /api/search:
    get:
      summary: 'Search properties'
      operationId: searchProperties
      description: '[Returns a list of filtered properties]'
      parameters:
        -
          in: query
          name: city
          description: 'City ID.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'City ID.'
            example: 1
        -
          in: query
          name: country
          description: 'Country ID.'
          example: 4
          required: false
          schema:
            type: integer
            description: 'Country ID.'
            example: 4
        -
          in: query
          name: geoobject
          description: 'Geoobject ID.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'Geoobject ID.'
            example: 1
        -
          in: query
          name: adults
          description: 'Number of adults.'
          example: 2
          required: false
          schema:
            type: integer
            description: 'Number of adults.'
            example: 2
        -
          in: query
          name: children
          description: 'Number of children.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'Number of children.'
            example: 1
        -
          in: query
          name: facilities
          description: 'List of facility IDs.'
          example:
            - 1
            - 2
            - 3
          required: false
          schema:
            type: array
            description: 'List of facility IDs.'
            example:
              - 1
              - 2
              - 3
            items:
              type: string
        -
          in: query
          name: price_from
          description: 'Minimum price.'
          example: 100
          required: false
          schema:
            type: integer
            description: 'Minimum price.'
            example: 100
        -
          in: query
          name: price_to
          description: 'Maximum price.'
          example: 200
          required: false
          schema:
            type: integer
            description: 'Maximum price.'
            example: 200
        -
          in: query
          name: start_date
          description: 'date Start date.'
          example: '2024-01-01'
          required: false
          schema:
            type: string
            description: 'date Start date.'
            example: '2024-01-01'
        -
          in: query
          name: end_date
          description: 'date End date.'
          example: '2024-01-03'
          required: false
          schema:
            type: string
            description: 'date End date.'
            example: '2024-01-03'
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  properties:
                    data:
                      -
                        id: 2
                        name: 'Qui velit ea.'
                        address: '2392 Zemlak Port Suite 655, 16225-4383, New York'
                        lat: '-54.8191470'
                        long: '-70.2183380'
                        apartments:
                          -
                            name: 'Mid size apartment'
                            type: null
                            size: null
                            beds_list: ''
                            bathrooms: 0
                            price: 0
                        photos: []
                        avg_rating: 8
                      -
                        id: 1
                        name: 'Provident enim est.'
                        address: '1487 Ignacio Alley Suite 794, 74215, New York'
                        lat: '13.2359740'
                        long: '-74.2809120'
                        apartments:
                          -
                            name: 'Cheap apartment'
                            type: null
                            size: null
                            beds_list: ''
                            bathrooms: 0
                            price: 0
                        photos: []
                        avg_rating: 7
                    links:
                      first: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                      last: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                      prev: null
                      next: null
                    meta:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      path: 'http://booking-com-simulation-laravel.test/api/search'
                      per_page: 10
                      to: 2
                      total: 2
                  facilities: []
                properties:
                  properties:
                    type: object
                    properties:
                      data:
                        type: array
                        example:
                          -
                            id: 2
                            name: 'Qui velit ea.'
                            address: '2392 Zemlak Port Suite 655, 16225-4383, New York'
                            lat: '-54.8191470'
                            long: '-70.2183380'
                            apartments:
                              -
                                name: 'Mid size apartment'
                                type: null
                                size: null
                                beds_list: ''
                                bathrooms: 0
                                price: 0
                            photos: []
                            avg_rating: 8
                          -
                            id: 1
                            name: 'Provident enim est.'
                            address: '1487 Ignacio Alley Suite 794, 74215, New York'
                            lat: '13.2359740'
                            long: '-74.2809120'
                            apartments:
                              -
                                name: 'Cheap apartment'
                                type: null
                                size: null
                                beds_list: ''
                                bathrooms: 0
                                price: 0
                            photos: []
                            avg_rating: 7
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 2
                            name:
                              type: string
                              example: 'Qui velit ea.'
                            address:
                              type: string
                              example: '2392 Zemlak Port Suite 655, 16225-4383, New York'
                            lat:
                              type: string
                              example: '-54.8191470'
                            long:
                              type: string
                              example: '-70.2183380'
                            apartments:
                              type: array
                              example:
                                -
                                  name: 'Mid size apartment'
                                  type: null
                                  size: null
                                  beds_list: ''
                                  bathrooms: 0
                                  price: 0
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                    example: 'Mid size apartment'
                                  type:
                                    type: string
                                    example: null
                                  size:
                                    type: string
                                    example: null
                                  beds_list:
                                    type: string
                                    example: ''
                                  bathrooms:
                                    type: integer
                                    example: 0
                                  price:
                                    type: integer
                                    example: 0
                            photos:
                              type: array
                              example: []
                            avg_rating:
                              type: integer
                              example: 8
                      links:
                        type: object
                        properties:
                          first:
                            type: string
                            example: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                          last:
                            type: string
                            example: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                          prev:
                            type: string
                            example: null
                          next:
                            type: string
                            example: null
                      meta:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 1
                          from:
                            type: integer
                            example: 1
                          last_page:
                            type: integer
                            example: 1
                          links:
                            type: array
                            example:
                              -
                                url: null
                                label: '&laquo; Previous'
                                active: false
                              -
                                url: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                                label: '1'
                                active: true
                              -
                                url: null
                                label: 'Next &raquo;'
                                active: false
                            items:
                              type: object
                              properties:
                                url:
                                  type: string
                                  example: null
                                label:
                                  type: string
                                  example: '&laquo; Previous'
                                active:
                                  type: boolean
                                  example: false
                          path:
                            type: string
                            example: 'http://booking-com-simulation-laravel.test/api/search'
                          per_page:
                            type: integer
                            example: 10
                          to:
                            type: integer
                            example: 2
                          total:
                            type: integer
                            example: 2
                  facilities:
                    type: array
                    example: []
      tags:
        - Public
      security: []
  '/api/properties/{property_id}':
    get:
      summary: 'Property details'
      operationId: propertyDetails
      description: '[Returns details of a property]'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  properties:
                    data:
                      -
                        id: 1
                        name: 'Aspernatur nostrum.'
                        address: '5716 Leann Point, 24974-6081, New York'
                        lat: '8.8008940'
                        long: '-82.9095500'
                        apartments:
                          -
                            name: 'Mid size apartment'
                            type: null
                            size: null
                            beds_list: ''
                            bathrooms: 0
                            price: 0
                        photos: []
                        avg_rating: null
                    links:
                      first: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                      last: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                      prev: null
                      next: null
                    meta:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      path: 'http://booking-com-simulation-laravel.test/api/search'
                      per_page: 10
                      to: 1
                      total: 1
                  facilities: []
                properties:
                  properties:
                    type: object
                    properties:
                      data:
                        type: array
                        example:
                          -
                            id: 1
                            name: 'Aspernatur nostrum.'
                            address: '5716 Leann Point, 24974-6081, New York'
                            lat: '8.8008940'
                            long: '-82.9095500'
                            apartments:
                              -
                                name: 'Mid size apartment'
                                type: null
                                size: null
                                beds_list: ''
                                bathrooms: 0
                                price: 0
                            photos: []
                            avg_rating: null
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: 'Aspernatur nostrum.'
                            address:
                              type: string
                              example: '5716 Leann Point, 24974-6081, New York'
                            lat:
                              type: string
                              example: '8.8008940'
                            long:
                              type: string
                              example: '-82.9095500'
                            apartments:
                              type: array
                              example:
                                -
                                  name: 'Mid size apartment'
                                  type: null
                                  size: null
                                  beds_list: ''
                                  bathrooms: 0
                                  price: 0
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                    example: 'Mid size apartment'
                                  type:
                                    type: string
                                    example: null
                                  size:
                                    type: string
                                    example: null
                                  beds_list:
                                    type: string
                                    example: ''
                                  bathrooms:
                                    type: integer
                                    example: 0
                                  price:
                                    type: integer
                                    example: 0
                            photos:
                              type: array
                              example: []
                            avg_rating:
                              type: string
                              example: null
                      links:
                        type: object
                        properties:
                          first:
                            type: string
                            example: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                          last:
                            type: string
                            example: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                          prev:
                            type: string
                            example: null
                          next:
                            type: string
                            example: null
                      meta:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 1
                          from:
                            type: integer
                            example: 1
                          last_page:
                            type: integer
                            example: 1
                          links:
                            type: array
                            example:
                              -
                                url: null
                                label: '&laquo; Previous'
                                active: false
                              -
                                url: 'http://booking-com-simulation-laravel.test/api/search?city=1&adults=2&children=1&page=1'
                                label: '1'
                                active: true
                              -
                                url: null
                                label: 'Next &raquo;'
                                active: false
                            items:
                              type: object
                              properties:
                                url:
                                  type: string
                                  example: null
                                label:
                                  type: string
                                  example: '&laquo; Previous'
                                active:
                                  type: boolean
                                  example: false
                          path:
                            type: string
                            example: 'http://booking-com-simulation-laravel.test/api/search'
                          per_page:
                            type: integer
                            example: 10
                          to:
                            type: integer
                            example: 1
                          total:
                            type: integer
                            example: 1
                  facilities:
                    type: array
                    example: []
      tags:
        - Public
      security: []
    parameters:
      -
        in: path
        name: property_id
        description: 'The ID of the property.'
        example: 3
        required: true
        schema:
          type: integer
  '/api/apartments/{apartment_id}':
    get:
      summary: 'Get apartment details'
      operationId: getApartmentDetails
      description: '[Returns details about a specific apartment]'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  name: 'Large apartment'
                  type: null
                  size: null
                  beds_list: ''
                  bathrooms: 0
                  facility_categories:
                    'First category':
                      - 'First facility'
                      - 'Second facility'
                    'Second category':
                      - 'Third facility'
                properties:
                  name:
                    type: string
                    example: 'Large apartment'
                  type:
                    type: string
                    example: null
                  size:
                    type: string
                    example: null
                  beds_list:
                    type: string
                    example: ''
                  bathrooms:
                    type: integer
                    example: 0
                  facility_categories:
                    type: object
                    properties:
                      'First category':
                        type: array
                        example:
                          - 'First facility'
                          - 'Second facility'
                        items:
                          type: string
                      'Second category':
                        type: array
                        example:
                          - 'Third facility'
                        items:
                          type: string
      tags:
        - Public
      security: []
    parameters:
      -
        in: path
        name: apartment_id
        description: 'The ID of the apartment.'
        example: 16
        required: true
        schema:
          type: integer
  /api/user/bookings:
    get:
      summary: 'List of user bookings'
      operationId: listOfUserBookings
      description: '[Returns preview list of all user bookings]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  apartment_name: 'Fugiat saepe sed.: Apartment'
                  start_date: '2023-05-11'
                  end_date: '2023-05-12'
                  guests_adults: 1
                  guests_children: 0
                  total_price: 0
                  cancelled_at: null
                  rating: null
                  review_comment: null
                properties:
                  id:
                    type: integer
                    example: 1
                  apartment_name:
                    type: string
                    example: 'Fugiat saepe sed.: Apartment'
                  start_date:
                    type: string
                    example: '2023-05-11'
                  end_date:
                    type: string
                    example: '2023-05-12'
                  guests_adults:
                    type: integer
                    example: 1
                  guests_children:
                    type: integer
                    example: 0
                  total_price:
                    type: integer
                    example: 0
                  cancelled_at:
                    type: string
                    example: null
                  rating:
                    type: string
                    example: null
                  review_comment:
                    type: string
                    example: null
      tags:
        - User
    post:
      summary: 'Create new booking'
      operationId: createNewBooking
      description: '[Creates new booking for authenticated user]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  apartment_name: 'Hic consequatur qui.: Apartment'
                  start_date: '2023-05-11 08:00:51'
                  end_date: '2023-05-12 08:00:51'
                  guests_adults: 2
                  guests_children: 1
                  total_price: 0
                  cancelled_at: null
                  rating: null
                  review_comment: null
                properties:
                  id:
                    type: integer
                    example: 1
                  apartment_name:
                    type: string
                    example: 'Hic consequatur qui.: Apartment'
                  start_date:
                    type: string
                    example: '2023-05-11 08:00:51'
                  end_date:
                    type: string
                    example: '2023-05-12 08:00:51'
                  guests_adults:
                    type: integer
                    example: 2
                  guests_children:
                    type: integer
                    example: 1
                  total_price:
                    type: integer
                    example: 0
                  cancelled_at:
                    type: string
                    example: null
                  rating:
                    type: string
                    example: null
                  review_comment:
                    type: string
                    example: null
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apartment_id:
                  type: string
                  description: ''
                  example: sunt
                start_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-05-10T11:51:53'
                end_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-05-10T11:51:53'
                guests_adults:
                  type: integer
                  description: ''
                  example: 5
                guests_children:
                  type: integer
                  description: ''
                  example: 7
              required:
                - apartment_id
                - start_date
                - end_date
  '/api/user/bookings/{id}':
    get:
      summary: 'View booking'
      operationId: viewBooking
      description: '[Returns details about a booking]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  apartment_name: 'Hic consequatur qui.: Apartment'
                  start_date: '2023-05-11 08:00:51'
                  end_date: '2023-05-12 08:00:51'
                  guests_adults: 2
                  guests_children: 1
                  total_price: 0
                  cancelled_at: null
                  rating: null
                  review_comment: null
                properties:
                  id:
                    type: integer
                    example: 1
                  apartment_name:
                    type: string
                    example: 'Hic consequatur qui.: Apartment'
                  start_date:
                    type: string
                    example: '2023-05-11 08:00:51'
                  end_date:
                    type: string
                    example: '2023-05-12 08:00:51'
                  guests_adults:
                    type: integer
                    example: 2
                  guests_children:
                    type: integer
                    example: 1
                  total_price:
                    type: integer
                    example: 0
                  cancelled_at:
                    type: string
                    example: null
                  rating:
                    type: string
                    example: null
                  review_comment:
                    type: string
                    example: null
      tags:
        - User
    put:
      summary: 'Update existing booking rating'
      operationId: updateExistingBookingRating
      description: '[Updates booking with new details]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 1
                  apartment_name: 'Hic consequatur qui.: Apartment'
                  start_date: '2023-05-11 08:00:51'
                  end_date: '2023-05-12 08:00:51'
                  guests_adults: 2
                  guests_children: 1
                  total_price: 0
                  cancelled_at: null
                  rating: null
                  review_comment: null
                properties:
                  id:
                    type: integer
                    example: 1
                  apartment_name:
                    type: string
                    example: 'Hic consequatur qui.: Apartment'
                  start_date:
                    type: string
                    example: '2023-05-11 08:00:51'
                  end_date:
                    type: string
                    example: '2023-05-12 08:00:51'
                  guests_adults:
                    type: integer
                    example: 2
                  guests_children:
                    type: integer
                    example: 1
                  total_price:
                    type: integer
                    example: 0
                  cancelled_at:
                    type: string
                    example: null
                  rating:
                    type: string
                    example: null
                  review_comment:
                    type: string
                    example: null
      tags:
        - User
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  type: integer
                  description: 'Must be between 1 and 10.'
                  example: 1
                review_comment:
                  type: string
                  description: 'Must be at least 20 characters.'
                  example: ssccvjhgbcmqkhmkpfqnbsqgprxyglhjrezjtayzubihntqqaqcetyntvvrnbytty
    delete:
      summary: 'Delete booking'
      operationId: deleteBooking
      description: '[Deletes a booking]'
      parameters:
        -
          in: header
          name: X-XSRF-TOKEN
          description: ''
          example: '{YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - User
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the booking.'
        example: 8
        required: true
        schema:
          type: integer
tags:
  -
    name: Authentication
    description: ''
  -
    name: Owner
    description: ''
  -
    name: Public
    description: ''
  -
    name: User
    description: ''
components:
  securitySchemes:
    default:
      type: apiKey
      name: X-XSRF-TOKEN
      in: header
      description: ''
security:
  -
    default: []
